create database mydatabase;
show databases; 
use mydatabase;

rename table mytable to customer; 

select * from customer limit 15;
#SOME QUESTIONS TO SOLVE FOR THE BEST ANALYSIS

# Q1) WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE?
 select gender, sum(purchase_amount) as total_revenue
 from customer
 group by gender;

# Q2) WHICH CUSTOMER USED DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT
select customer_id, purchase_amount
from customer where discount_applied = 'Yes'
and 
purchase_amount > (select avg(purchase_amount) from customer);

# Q3) WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING
select item_purchased, round(avg(review_rating),1) 
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

# Q4) COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING
select round(avg(purchase_amount),1), shipping_type
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type;

# Q5) DO SUBSCRIBED CUTOMERS SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBERS AND NON SUBSCRIBERS
select subscription_status,
count(customer_id) as total_customer,
avg(purchase_amount) as avg_spent,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg_spent, total_revenue desc;

# Q6) WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNT APPLIED
select item_purchased,
round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),0) as disc_rate
from customer
group by item_purchased
order by disc_rate desc
limit 5;

# Q7) SEGMENT CUSTOMERS INTO NEW, RETURNING, LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASES, SHOW THE COUNT OF EACH SEGMENT
with customer_type as (
select customer_id, previous_purchases,
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment 
from customer
)

select customer_segment, count(*)
from customer_type
group by customer_segment;

# Q8) WHAT ARE THE TOP 3 MOST PURCHASED PRODUCTS WITHIN EACH CATEGORY
with rank_counts as (
select category, item_purchased, count(customer_id) as total_counts,
dense_rank() over (partition by category order by count(customer_id) desc) as rank_items
from customer
group by category, item_purchased
)

select rank_items, category, item_purchased, total_counts
from rank_counts
where rank_items <= 3;

# Q9) ARE CUSTOMERS WHO ARE REPEAT BUYERS( MORE THA 5 PREVIOUS PURCHASES ) ARE LIKELY TO BE SUBSCRIBER?
select subscription_status,
count(customer_id) as total_customers
from customer
where previous_purchases>5
group by subscription_status;

# Q10) WHAT IS THE REVENUE CONTRIBUTION OF EACH AGE GROUP
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc  ;